In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_excel('data.xlsx')

In [3]:
data.head(3)

,序号,来源详情,您宝宝的性别,您的宝宝的出生日期：,(1)您有几个孩子,(2)个孩子，这是您的第___个孩子,宝宝的主要抚养人,请问宝宝的家庭类型是,宝宝母亲的年龄（周岁）,宝宝母亲的文化程度:,...,拥有足量的与年龄适宜的玩具,对孩子任何事情都要干涉,给孩子的诉说、表达或申辩的机会,带孩子到商店、公园,赞赏孩子的好奇心，有意识培养孩子兴趣,无端向孩子发脾气,有意识帮助孩子认知事物，扩大词汇,保持孩子活动的房间清洁、整齐,对孩子的需求能够作出及时的回应.1,总分
0,1,NaN,男,2023-06-20,1,2,保姆阿姨,联合家庭（宝宝、父母、祖父母（或外祖父母）三代一起居住）,23,初中及以下,...,(跳过),(跳过),(跳过),(跳过),(跳过),(跳过),(跳过),(跳过),(跳过),62
1,2,NaN,男,2020-06-15,2,2,父母,核心家庭（宝宝与父母一起居住）,30,本科,...,总是,总是,总是,总是,总是,很少,总是,总是,总是,240
2,3,NaN,女,2022-03-09,2,2,父母,联合家庭（宝宝、父母、祖父母（或外祖父母）三代一起居住）,30,大专,...,(跳过),(跳过),(跳过),(跳过),(跳过),(跳过),(跳过),(跳过),(跳过),132

将中文转化为数字（注意此时还没有分正负）

In [48]:
map = {  
    '从不': 1,  
    '很少': 2,  
    '有时': 3,  
    '经常': 4,  
    '总是': 5,
    '(跳过)' : 0,
    '(空)' : 0
}  

for col in data.columns[16-1:]:
        data[col] = data[col].replace(map)

C:\Users\eason\AppData\Local\Temp\ipykernel_51760\2914849974.py:11: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data[col] = data[col].replace(map)

负面问题乘以-1的权重

In [8]:
feature = data.columns
print(feature)

Index(['序号', '来源详情', '您宝宝的性别', '您的宝宝的出生日期：', '(1)您有几个孩子', '(2)个孩子，这是您的第___个孩子',
       '宝宝的主要抚养人', '请问宝宝的家庭类型是', '宝宝母亲的年龄（周岁）', '宝宝母亲的文化程度:',
       ...
       '拥有足量的与年龄适宜的玩具', '对孩子任何事情都要干涉', '给孩子的诉说、表达或申辩的机会', '带孩子到商店、公园',
       '赞赏孩子的好奇心，有意识培养孩子兴趣', '无端向孩子发脾气', '有意识帮助孩子认知事物，扩大词汇', '保持孩子活动的房间清洁、整齐',
       '对孩子的需求能够作出及时的回应.1', '总分'],
      dtype='object', length=142)

In [49]:
negative_col = [
    '终日在外忙碌，很少有时间见到孩子',
    '把孩子捆扎得很紧，孩子四肢手足难以活动',
    '不太喜欢孩子，不愿和孩子在一起',
    '为了家庭或孩子的事情争吵、闹别扭',
    '当孩子出现与平常不一样的表现便很着急',
    '总担心孩子出事，把孩子限制得很死',
    '感到带孩子很累、很烦',
    '凭自己心情对孩子忽冷忽热',
    '感到带孩子很烦、很累',
    '用恐怖的意象或故事(如大灰狼)吓唬孩子的自主行为',
    '总担心出事，把孩子限制得很死',
    '惩罚(叱骂、打屁股、罚站等)孩子',
    '不喜欢孩子，不愿和孩子在一起',
    '凭自己心情对孩子忽冷忽热.1',
    '为家庭或孩子的事情而争吵、闹别扭',
    '用恐怖的意象或故事(如大灰狼)吓阻孩子的自主行为',
    '凭自己心情对孩子忽冷忽热.2',
    '亲子出现敌对或冲突',
    '总担心出事，把孩子限制得很死.1',
    '感到带孩子很累、很烦.1',
    '惩罚(叱骂、打屁股、罚站等)孩子.1',
    '为家庭或孩子的事情而争吵',
    '经常强迫孩子多吃一点',
    '对孩子任何事情都要干涉',
    '无端向孩子发脾气'
]

for col in negative_col:
    data[col] *= -1

In [63]:
data.head()

,序号,来源详情,您宝宝的性别,您的宝宝的出生日期：,(1)您有几个孩子,(2)个孩子，这是您的第___个孩子,宝宝的主要抚养人,请问宝宝的家庭类型是,宝宝母亲的年龄（周岁）,宝宝母亲的文化程度:,...,拥有足量的与年龄适宜的玩具,对孩子任何事情都要干涉,给孩子的诉说、表达或申辩的机会,带孩子到商店、公园,赞赏孩子的好奇心，有意识培养孩子兴趣,无端向孩子发脾气,有意识帮助孩子认知事物，扩大词汇,保持孩子活动的房间清洁、整齐,对孩子的需求能够作出及时的回应.1,总分
0,1,NaN,男,2023/6/20,1,2,保姆阿姨,联合家庭（宝宝、父母、祖父母（或外祖父母）三代一起居住）,23,初中及以下,...,0,0,0,0,0,0,0,0,0,62
1,2,NaN,男,2020/6/15,2,2,父母,核心家庭（宝宝与父母一起居住）,30,本科,...,5,-5,5,5,5,-2,5,5,5,240
2,3,NaN,女,2022/3/9,2,2,父母,联合家庭（宝宝、父母、祖父母（或外祖父母）三代一起居住）,30,大专,...,0,0,0,0,0,0,0,0,0,132
4,5,NaN,男,2023/3/15,2,2,父母,核心家庭（宝宝与父母一起居住）,33,大专,...,0,0,0,0,0,0,0,0,0,160
5,6,NaN,男,2023/3/19,2,2,父母,联合家庭（宝宝、父母、祖父母（或外祖父母）三代一起居住）,29,本科,...,0,0,0,0,0,0,0,0,0,106

In [51]:
# dicList = [
#     {'直接访问': 1},
#     {'男': 0, '女': 1},
#     {'1': 1, '2': 2, '3': 3, '一': 1, '二': 2, '三': 3, '俩': 2, '两': 2, '两个': 2, '一个': 1, '4': 4, '四': 4, '5': 5, '五': 5, '三个': 3, '四个': 4, '五个': 5},
#     {'1': 1, '2': 2, '3': 3, '一': 1, '二': 2, '三': 3, '俩': 2, '两': 2, '两个': 2, '一个': 1, '4': 4, '四': 4, '5': 5, '五': 5, '三个': 3, '四个': 4, '五个': 5},
#     {'保姆阿姨': 0, '父母': 1, '外祖父母或祖父母': 2},
#     {'联合家庭（宝宝、父母、祖父母（或外祖父母）三代一起居住）': 0, '核心家庭（宝宝与父母一起居住）': 1, '其他（单亲、再婚等）': 2}
# ]

# for i in range(6):
#     data.replace({feature[i]: dicList[i]}, inplace=True)

定义一个函数来检查内容是否为整数int，将内容本应该为整数，但含有非法值的样本直接删去

In [52]:
def remove_not_int (df, columns_to_check):
    def is_numeric(s):
        try:  
            int(s)
            return True
        except ValueError: 
            return False

    mask = df[columns_to_check].applymap(is_numeric).all(axis=1)  

    df_filtered = df[mask]  

    return df_filtered

In [53]:
columns_to_check = ['(1)您有几个孩子', '(2)个孩子，这是您的第___个孩子', '宝宝母亲的年龄（周岁）', '宝宝父亲的年龄（周岁）'] 
data = remove_not_int(data, columns_to_check)

C:\Users\eason\AppData\Local\Temp\ipykernel_51760\1061213373.py:9: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  mask = df[columns_to_check].applymap(is_numeric).all(axis=1)

将筛选过非法值的列转化为int类型

In [59]:
data['(1)您有几个孩子'] = data['(1)您有几个孩子'].astype(int)
data['(2)个孩子，这是您的第___个孩子'] = data['(2)个孩子，这是您的第___个孩子'].astype(int)

删除不符合常理的数值

In [60]:
data = data[data['(1)您有几个孩子'] <= 10]
data = data[data['(2)个孩子，这是您的第___个孩子'] <= 10]

In [61]:
data.head()

,序号,来源详情,您宝宝的性别,您的宝宝的出生日期：,(1)您有几个孩子,(2)个孩子，这是您的第___个孩子,宝宝的主要抚养人,请问宝宝的家庭类型是,宝宝母亲的年龄（周岁）,宝宝母亲的文化程度:,...,拥有足量的与年龄适宜的玩具,对孩子任何事情都要干涉,给孩子的诉说、表达或申辩的机会,带孩子到商店、公园,赞赏孩子的好奇心，有意识培养孩子兴趣,无端向孩子发脾气,有意识帮助孩子认知事物，扩大词汇,保持孩子活动的房间清洁、整齐,对孩子的需求能够作出及时的回应.1,总分
0,1,NaN,男,2023/6/20,1,2,保姆阿姨,联合家庭（宝宝、父母、祖父母（或外祖父母）三代一起居住）,23,初中及以下,...,0,0,0,0,0,0,0,0,0,62
1,2,NaN,男,2020/6/15,2,2,父母,核心家庭（宝宝与父母一起居住）,30,本科,...,5,-5,5,5,5,-2,5,5,5,240
2,3,NaN,女,2022/3/9,2,2,父母,联合家庭（宝宝、父母、祖父母（或外祖父母）三代一起居住）,30,大专,...,0,0,0,0,0,0,0,0,0,132
4,5,NaN,男,2023/3/15,2,2,父母,核心家庭（宝宝与父母一起居住）,33,大专,...,0,0,0,0,0,0,0,0,0,160
5,6,NaN,男,2023/3/19,2,2,父母,联合家庭（宝宝、父母、祖父母（或外祖父母）三代一起居住）,29,本科,...,0,0,0,0,0,0,0,0,0,106

In [62]:
data.describe()

,序号,(1)您有几个孩子,(2)个孩子，这是您的第___个孩子,0~1岁儿童家庭养育环境问卷—孩子活动的房间保持清洁、整齐,让孩子参加早期潜能开发活动,终日在外忙碌，很少有时间见到孩子,关注孩子维生素/微量元素的营养状况,孩子由亲生父母亲自看护,把孩子捆扎得很紧，孩子四肢手足难以活动,带孩子离家到户外活动,...,拥有足量的与年龄适宜的玩具,对孩子任何事情都要干涉,给孩子的诉说、表达或申辩的机会,带孩子到商店、公园,赞赏孩子的好奇心，有意识培养孩子兴趣,无端向孩子发脾气,有意识帮助孩子认知事物，扩大词汇,保持孩子活动的房间清洁、整齐,对孩子的需求能够作出及时的回应.1,总分
count,50947.000000,50947.000000,50947.000000,50947.000000,50947.000000,50947.000000,50947.000000,50947.000000,50947.000000,50947.000000,...,50947.000000,50947.000000,50947.000000,50947.000000,50947.000000,50947.000000,50947.000000,50947.000000,50947.000000,50947.000000
mean,26431.851316,1.561250,1.442793,0.124698,0.103303,-0.053291,0.116415,0.128212,-0.040454,0.106778,...,3.761497,-2.240407,3.838675,3.913145,3.903351,-1.691621,3.818341,3.884429,3.906432,192.807506
std,15126.831036,0.584037,0.559428,0.743714,0.636245,0.376098,0.703148,0.763609,0.294802,0.654191,...,1.429900,1.130665,1.401982,1.406089,1.415934,1.029327,1.411322,1.409595,1.396510,29.258994
min,1.000000,0.000000,-1.000000,0.000000,0.000000,-5.000000,0.000000,0.000000,-5.000000,0.000000,...,0.000000,-5.000000,0.000000,0.000000,0.000000,-5.000000,0.000000,0.000000,0.000000,32.000000
25%,13393.500000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,3.000000,-3.000000,4.000000,4.000000,4.000000,-2.000000,4.000000,4.000000,4.000000,178.000000
50%,26452.000000,2.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,4.000000,-2.000000,4.000000,4.000000,4.000000,-2.000000,4.000000,4.000000,4.000000,194.000000
75%,39470.500000,2.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,5.000000,-2.000000,5.000000,5.000000,5.000000,-1.000000,5.000000,5.000000,5.000000,212.000000
max,52640.000000,8.000000,10.000000,5.000000,5.000000,0.000000,5.000000,5.000000,0.000000,5.000000,...,5.000000,0.000000,5.000000,5.000000,5.000000,0.000000,5.000000,5.000000,5.000000,265.000000